export const roleMenus = {
  ADMIN: [
    { to: '/admin/dashboard', icon: 'dashboard', label: '平台概览' },
    { to: '/admin/user-audit', icon: 'fact_check', label: '用户审核' },
    { to: '/admin/user-role', icon: 'manage_accounts', label: '用户与角色' },
    { to: '/admin/node-status', icon: 'hub', label: '节点状态' },
    { to: '/admin/contract-config', icon: 'settings_applications', label: '合约配置' },
    { to: '/admin/logs', icon: 'article', label: '操作日志' },
  ],
  FARMER: [
    { to: '/farmer/dashboard', icon: 'dashboard', label: '工作台' },
    { to: '/farmer/batch-create', icon: 'add_box', label: '新建批次' },
    { to: '/farmer/batches', icon: 'edit_note', label: '农事记录' },
    { to: '/farmer/batches', icon: 'list_alt', label: '我的批次' },
    { to: '/farmer/batches', icon: 'receipt_long', label: '批次详情' },
  ],
  PROCESSOR: [
    { to: '/processor/dashboard', icon: 'dashboard', label: '工作台' },
    { to: '/processor/pending', icon: 'inventory_2', label: '待加工批次' },
    { to: '/processor/process-record/SC20240521001', icon: 'science', label: '加工与质检' },
    { to: '/processor/file-upload/SC20240521001', icon: 'upload_file', label: '上传与验真' },
    { to: '/processor/batch-detail/SC20240521001', icon: 'info', label: '批次详情' },
  ],
  LOGISTICS: [
    { to: '/logistics/dashboard', icon: 'dashboard', label: '工作台' },
    { to: '/logistics/pending', icon: 'view_list', label: '待运输批次' },
    { to: '/logistics/transport-record/SC20240521001', icon: 'local_shipping', label: '运输记录' },
    { to: '/logistics/temp-record/SC20240521001', icon: 'thermostat', label: '温湿度记录' },
    { to: '/logistics/batch-detail/SC20240521001', icon: 'info', label: '批次详情' },
  ],
  RETAIL: [
    { to: '/retail/dashboard', icon: 'dashboard', label: '工作台' },
    { to: '/retail/pending', icon: 'inventory', label: '待入库批次' },
    { to: '/retail/retail-record/SC20240521001', icon: 'store', label: '入库与上架' },
    { to: '/retail/sale-status/SC20240521001', icon: 'sell', label: '销售状态' },
    { to: '/retail/qrcode/SC20240521001', icon: 'qr_code_2', label: '二维码' },
    { to: '/retail/batch-detail/SC20240521001', icon: 'info', label: '批次详情' },
  ],
  REGULATOR: [
    { to: '/regulator/dashboard', icon: 'dashboard', label: '风险看板' },
    { to: '/regulator/search', icon: 'search', label: '综合检索' },
    { to: '/regulator/abnormal', icon: 'warning', label: '异常批次' },
    { to: '/regulator/batch-detail/SC20240521001', icon: 'description', label: '批次详情' },
    { to: '/regulator/flag/SC20240521001', icon: 'flag', label: '标记异常' },
    { to: '/regulator/evidence/SC20240521001', icon: 'shield', label: '证据链' },
    { to: '/regulator/audit/SC20240521001', icon: 'gavel', label: '审计处理' },
    { to: '/regulator/audit-logs', icon: 'history', label: '审计日志' },
    { to: '/regulator/stats', icon: 'bar_chart', label: '风险统计' },
  ],
}
